# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# createSiteFprints__modelBuilder.py
# Created on: 2020-05-26 13:44:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
nga_inventory_canon = "nga_inventory_canon"
nga_inventory_canon_Layer = "nga_inventory_canon_Layer"
nga_inventory_canon_Layer__3_ = nga_inventory_canon_Layer
SERC = "SERC"
SERC__ngaFootprints__UTM_shp = "E:\\MaggieData\\ProposalStuff\\Biodiversity_2020\\Sites\\createDensityMaps\\temp\\SERC__ngaFootprints__UTM.shp"
SERC__ngaFootprints__UTM_shp__4_ = SERC__ngaFootprints__UTM_shp
SERC__ngaFootprints__UTM_shp__6_ = SERC__ngaFootprints__UTM_shp__4_
SERC__ngaFootprints__UTM_shp__5_ = SERC__ngaFootprints__UTM_shp__6_
SERC__ngaFootprints__UTM_shp__3_ = SERC__ngaFootprints__UTM_shp__5_
SERC__ngaFootprints__strips_shp = "E:\\MaggieData\\ProposalStuff\\Biodiversity_2020\\Sites\\createDensityMaps\\SERC__ngaFootprints__strips.shp"
SERC__ngaFootprints__strips_shp__2_ = SERC__ngaFootprints__strips_shp
SERC__ngaFootprints__strips_shp__4_ = SERC__ngaFootprints__strips_shp__2_
UTM_Zone_Boundaries = "UTM_Zone_Boundaries"
SERC__clippedUTM_shp = "E:\\MaggieData\\ProposalStuff\\Biodiversity_2020\\Sites\\createDensityMaps\\temp\\SERC__clippedUTM.shp"
Modified_Input_Features = SERC__clippedUTM_shp

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(nga_inventory_canon, nga_inventory_canon_Layer, "", "", "SHAPE SHAPE VISIBLE NONE;OBJECTID OBJECTID VISIBLE NONE;STRIP_ID STRIP_ID VISIBLE NONE;SCENE_ID SCENE_ID VISIBLE NONE;STATUS STATUS VISIBLE NONE;SENSOR SENSOR VISIBLE NONE;CATALOG_ID CATALOG_ID VISIBLE NONE;ORDER_ID ORDER_ID VISIBLE NONE;PROD_CODE PROD_CODE VISIBLE NONE;COUNTRY COUNTRY VISIBLE NONE;SPEC_TYPE SPEC_TYPE VISIBLE NONE;ACQ_TIME ACQ_TIME VISIBLE NONE;CLOUDCOVER CLOUDCOVER VISIBLE NONE;CENT_LAT CENT_LAT VISIBLE NONE;CENT_LONG CENT_LONG VISIBLE NONE;BANDS BANDS VISIBLE NONE;COLUMNS COLUMNS VISIBLE NONE;ROWS ROWS VISIBLE NONE;BITS_PIXEL BITS_PIXEL VISIBLE NONE;FILE_FMT FILE_FMT VISIBLE NONE;OFF_NADIR OFF_NADIR VISIBLE NONE;SUN_ELEV SUN_ELEV VISIBLE NONE;EXPOSURE EXPOSURE VISIBLE NONE;SCAN_DIR SCAN_DIR VISIBLE NONE;COLL_GSD COLL_GSD VISIBLE NONE;PROD_GSD PROD_GSD VISIBLE NONE;DET_PITCH DET_PITCH VISIBLE NONE;LINE_RATE LINE_RATE VISIBLE NONE;REF_HEIGHT REF_HEIGHT VISIBLE NONE;ABSCALFACT ABSCALFACT VISIBLE NONE;BANDWIDTH BANDWIDTH VISIBLE NONE;TDI TDI VISIBLE NONE;XTRACKVA XTRACKVA VISIBLE NONE;INTRACKVA INTRACKVA VISIBLE NONE;O_FILENAME O_FILENAME VISIBLE NONE;O_FILEPATH O_FILEPATH VISIBLE NONE;O_DRIVE O_DRIVE VISIBLE NONE;S_FILENAME S_FILENAME VISIBLE NONE;S_FILEPATH S_FILEPATH VISIBLE NONE;PREVIEWJPG PREVIEWJPG VISIBLE NONE;PREVIEWURL PREVIEWURL VISIBLE NONE;ADDED_DATE ADDED_DATE VISIBLE NONE;MOD_DATE MOD_DATE VISIBLE NONE;RCVD_DATE RCVD_DATE VISIBLE NONE;NGA_NAME NGA_NAME VISIBLE NONE;FILE_SZ FILE_SZ VISIBLE NONE;avsunazim avsunazim VISIBLE NONE;avtargetaz avtargetaz VISIBLE NONE;stereopair stereopair VISIBLE NONE;pairname pairname VISIBLE NONE;ACQ_DATE ACQ_DATE VISIBLE NONE;acq_year acq_year VISIBLE NONE;prod_short prod_short VISIBLE NONE;SHAPE_Length SHAPE_Length VISIBLE NONE;SHAPE_Area SHAPE_Area VISIBLE NONE")

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(nga_inventory_canon_Layer, "INTERSECT", SERC, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Project
arcpy.Project_management(nga_inventory_canon_Layer__3_, SERC__ngaFootprints__UTM_shp, "PROJCS['WGS_1984_UTM_Zone_18N',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-75.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "", "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "NO_PRESERVE_SHAPE", "", "NO_VERTICAL")

# Process: Add Field (4)
arcpy.AddField_management(SERC__ngaFootprints__UTM_shp, "dateStr", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(SERC__ngaFootprints__UTM_shp__4_, "dateStr", "!SCENE_ID!.split('_')[1][0:8]", "PYTHON_9.3", "")

# Process: Add Field (2)
arcpy.AddField_management(SERC__ngaFootprints__UTM_shp__6_, "stripName", "TEXT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(SERC__ngaFootprints__UTM_shp__5_, "stripName", "'{}_{}_{}_{}'.format( !SENSOR!, !dateStr!, !PROD_CODE!, !CATALOG_ID!)", "PYTHON_9.3", "")

# Process: Dissolve
arcpy.Dissolve_management(SERC__ngaFootprints__UTM_shp__3_, SERC__ngaFootprints__strips_shp, "stripName", "STRIP_ID FIRST;SCENE_ID FIRST;SENSOR FIRST;CATALOG_ID LAST;ORDER_ID LAST;PROD_CODE LAST;COUNTRY LAST;SPEC_TYPE LAST;ACQ_TIME LAST;CLOUDCOVER MEAN;BANDS LAST;OFF_NADIR MEAN;SUN_ELEV MEAN;SCAN_DIR LAST;ABSCALFACT MAX;BANDWIDTH MAX;S_FILEPATH LAST;NGA_NAME LAST;avsunazim MEAN;avtargetaz MEAN;stereopair LAST;pairname LAST;ACQ_DATE LAST;acq_year LAST;prod_short LAST;stripName LAST", "SINGLE_PART", "DISSOLVE_LINES")

# Process: Add Field (3)
arcpy.AddField_management(SERC__ngaFootprints__strips_shp, "one", "SHORT", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(SERC__ngaFootprints__strips_shp__2_, "one", "1", "PYTHON_9.3", "")

# Process: Clip
arcpy.Clip_analysis(UTM_Zone_Boundaries, SERC, SERC__clippedUTM_shp, "")

# Process: Add Geometry Attributes
arcpy.AddGeometryAttributes_management(SERC__clippedUTM_shp, "AREA_GEODESIC", "", "", "")

